### ISSUE TITLE
MobFox sdk without mopub integration

### ISSUE THREAD

**Issue by MattiaConfalonieri** [mobfox/MobFox-iOS-SDK#10]
In my project i have already integrated the Mopub SDK to manage my direct adv offers, when i import mob fox sdks i receive a duplicate symbols error, there is a way to get a mob fox sdks version without mop integration?

**Comment by michal-gecko** [comment]
Hi,
MobFox SDK relies on MoPub for MRAID ads. If you don't want to display MRAID ads I should be able to prepare a version without MoPub for you, but please keep in mind it would be rather experimental builds.

**Comment by MattiaConfalonieri** [comment]
No thanks, is not a problem, maybe i integrate MobFox in future. Thank for help.
