### ISSUE TITLE
Mobfoxbannerview click not working iOS

### ISSUE THREAD

**Issue by gilbertngandu** [mobfox/MobFox-iOS-SDK#12]
Hi,
I am having issues with mobfoxbannerview on iOS. The ad is displaying but the click event doesnt work. When i request manually (from the browser) the xml seems correct and i can see the click url. The bannerview is in front of all the views.

![xml](https://cloud.githubusercontent.com/assets/5882052/7766183/f947fa9e-0066-11e5-9095-f64e75d9fb22.png)

**Comment by michal-gecko** [comment]
Hi,
Sorry for the problem. Could you perhaps provide the whole XML returned from the server? Also, are you using the latest version of the SDK?

**Comment by gilbertngandu** [comment]
This is the url am using 
http://viacell.co.za/mAds/md.request.php?rt=api&r_type=native&r_resp=json&n_img=icon&n_txt=headline&s=26f59f524c7024c501f801504a7eb645&i=2.122.29.194&u=Mozilla/5.0%20%28iPhone;%20U;%20CPU%20iPhone%20OS%203_0%20like%20Mac%20OS%20X;%20en-us%29%20AppleWebKit/528.18%20%28KHTML,%20like%20Gecko%29%20Version/4.0%20Mobile/7A341%20Safari/528.16&o_iosadvid=68753A44-4D6F-1226-9C60-0050E4C00067

and the response is in my previous post

I am using sdk 6.0.0 

It works perfectly on the old version AdSdk but i had to upgrade to mobfox 6.0.0 because the old version does have 64bit support and i couldnt submit the app.

**Comment by michal-gecko** [comment]
Hi,
Thanks for response. I see the bug in code, I should be able to prepare a fixed build within next hour.

**Comment by gilbertngandu** [comment]
Thank you so much.

**Comment by michal-gecko** [comment]
Hi again,
Prepared a promised fix. It will probably take some time before it's available on control panel, so I'm also posting link here not to waste time waiting: http://mobia.pl/geckonew/ftp/MobFox/fixes/MobFox.embeddedframework-6.2.2.zip

Thanks for patience and help in debugging it :-)

**Comment by gilbertngandu** [comment]
Hi,
Now it's not showing the ad but when i debug is see that the mobfoxBannerViewDidLoadMobFoxAd event is triggered. In the next fix can you make the _tapThroughURL available (public)

**Comment by michal-gecko** [comment]
Strange, just tried it again and got the ad (clickable). Did you clean your project after update?

**Comment by gilbertngandu** [comment]
can you test using the following request url
http://viacell.co.za/mAds/md.request.php
publisher id=26f59f524c7024c501f801504a7eb645
i tried using sdk 6.1.0 and 6.0.1 but it's not clickable as well

**Comment by michal-gecko** [comment]
Hi,
I'm testing on the newest build I've sent link to today (http://mobia.pl/geckonew/ftp/MobFox/fixes/MobFox.embeddedframework-6.2.2.zip). In older versions the click indeed didn't work.

**Comment by gilbertngandu** [comment]
after initializing the bannerView i do the following:
self.bannerView.adspacewidth = 320;
self.bannerView.adspaceHeight = 50;
self.bannerView.adspaceStrict = NO;
self.bannerView.requestURL = @"http://viacell.co.za/mAds/md.request.php"
self.bannerView.delegate = self
[self.view.addSubview:self.bannerView];
This shows the ad without click in older versions and nothing in the new 6.2.2 version. Is there an extra parameter that i didnt set.

**Comment by michal-gecko** [comment]
Nothing more should be needed. Do you obtain the 
- (void)mobfoxBannerViewDidLoadMobFoxAd:(MobFoxBannerView *)banner
notification? If yes, are you placing the banner in correct position on screen after it is received?

**Comment by gilbertngandu** [comment]
i am not doing anything in the didlloadmobfox. The position is set when i initialize the mobfoxbannerview
self.bannerview = [[mobfoxbannerview alloc] initwithframe:cgrectmake(....

**Comment by michal-gecko** [comment]
Hmm, so to make sure please implement it like:

- (void)slideInBannerView:(MobFoxBannerView *)banner {
  
banner.bounds = CGRectMake(0, 0, banner.bounds.size.width, banner.bounds.size.height);

banner.center = CGPointMake(self.view.bounds.size.width/2.0, self.view.bounds.size.height - banner.bounds.size.height/2.0);

}

**Comment by gilbertngandu** [comment]
Voila!!!
It's working now. I also had to return YES in mobfoxBannerViewActionBegin. and put 
banner.bounds = CGRectMake(0, 0, banner.bounds.size.width, banner.bounds.size.height);

banner.center = CGPointMake(self.view.bounds.size.width/2.0, self.view.bounds.size.height - banner.bounds.size.height/2.0);

inside didload


Thanks a lot I really appreciate!
Great service Mobfox!

**Comment by michal-gecko** [comment]
Ha, glad to know it worked! :-)
