### ISSUE TITLE
In MPHTMLBannerCustomEventMF.m I am getting warning Incompatible pointer types sending 'MPAdConfiguration *' to parameter of type 'MPAdConfigurationMF *'

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#13]

**Comment by nabriski** [comment]
This may be an XCode issues, please try to ignore this and see if it all works properly.

**Comment by harithahdasan** [comment]
Ok

**Comment by harithahdasan** [comment]
Hi...I am testing this Mobfox SDK for Banner ads,On clicking a button Banner Ad is coming but while clicking that banner ad it is showing a blank view.But when I paste the tap url  in any browser ,it is showing a webpage.Why clickUrl not displaying any content in my simulator??

This is my request string:
http://my.mobfox.com/request.php?r_type=banner&rt=api&u=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%208_4%20like%20Mac%20OS%20X%29%20AppleWebKit%2F600.1.4%20%28KHTML%2C%20like%20Gecko%29%20Mobile%2F12H4125a&o_iosadvid=D11C776B-F250-46DD-9214-9559AF012C22&v=6.2.2&s=a7c07f113cc83e87e82f95f0ca8be1dc&iphone_osversion=8.4&r_random=1350&m=live&i=158.25.45.46
Here is the screenshot of the view presented after tapping clicker
![screen shot 2015-07-21 at 12 18 07 pm](https://cloud.githubusercontent.com/assets/13059550/8794666/3b674040-2fa3-11e5-93c4-0a25ff35c56f.png)

**Comment by nabriski** [comment]
Hi,
Please paste your banner integration code.
Also you can test it on the demo app. If it works please compare your code to the demo app's.

**Comment by nabriski** [comment]
Closing this issue as the topic no longer reflects the problem. Please reopen this in a new issue.
