### ISSUE TITLE
Duplicate symbol error when working with the latest MoPub

### ISSUE THREAD

**Issue by CyrilChyi** [mobfox/MobFox-iOS-SDK#14]
Though you have added suffix to the MoPub classes, we still can't compile when integrating your SDK when we already have MoPub in our project. We think you should add suffix to the global variable names as well. Here's part of  the errors.

duplicate symbol _kAdTypeHtml in:
    /.../Objects-normal/x86_64/MPAdConfiguration.o
    /.../MobFox.framework/MobFox(MobFox)

duplicate symbol _kAdTypeInterstitial in:
    /.../Objects-normal/x86_64/MPAdConfiguration.o
    /.../MobFox(MobFox)

**Comment by nabriski** [comment]
Thanks, I'll fix it soon.
