### ISSUE TITLE
BannerAd tap url not displaying any content ..

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#15]
Hi...I am testing this Mobfox SDK for Banner ads,.I created a separate project and added the sdk classes and all dependencies.I placed a button inside the  UI and On clicking that button Banner Ad is displaying but while clicking that banner ad ,it is showing a blank view.But when I paste the click url in any browser ,it is showing a webpage.Why clickUrl not displaying any content in my simulator??(Actually few weeks before I was able to direct to a page by clicking the banner Ad,But now it is like this way)What is causing the actual problem?

http://my.mobfox.com/request.php?r_type=banner&rt=api&u=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%208_4%20like%20Mac%20OS%20X%29%20AppleWebKit%2F600.1.4%20%28KHTML%2C%20like%20Gecko%29%20Mobile%2F12H4125a&o_iosadvid=D11C776B-F250-46DD-9214-9559AF012C22&v=6.2.2&s=a7c07f113cc83e87e82f95f0ca8be1dc&iphone_osversion=8.4&r_random=1350&m=live&i=158.25.45.46
![3b674040-2fa3-11e5-93c4-0a25ff35c56f](https://cloud.githubusercontent.com/assets/13059550/8799902/761f7180-2fcb-11e5-8603-9192f74f6bc0.png)

**Comment by nabriski** [comment]
Hi, can you please share your banner integration code?

**Comment by harithahdasan** [comment]
@nabriski :Hi ..is this the portion of code u asking for????
![screen shot 2015-07-21 at 5 22 42 pm](https://cloud.githubusercontent.com/assets/13059550/8800117/a060d342-2fcd-11e5-8800-30e68f707fb8.png)

**Comment by harithahdasan** [comment]
Even in your demo app when i replace the test Publisher Id to my live publisher Id,some cases I get a blank page on tapping bannerAd...

**Comment by harithahdasan** [comment]
@nabriski :Today When I click on the add ,this is the response.
![screen shot 2015-07-22 at 9 35 04 am](https://cloud.githubusercontent.com/assets/13059550/8817785/867ed0cc-3055-11e5-8fa0-e8a05c4a5a3c.png)
And when I tried to open that clickurl in desktop browser i got the below output..
![screen shot 2015-07-22 at 9 36 16 am](https://cloud.githubusercontent.com/assets/13059550/8817807/e33985aa-3055-11e5-95a0-94b4af29d529.png)

**Comment by nabriski** [comment]
This may be a server side problem with the demand you are getting. I'll forward this to the MobFox server team.

**Comment by harithahdasan** [comment]
Ok thanks...

**Comment by nabriski** [comment]
The MobFox server team is investigating this, can you please paste here the markup you are getting in the response? It will help them, thanks.

**Comment by harithahdasan** [comment]
Hi @nabriski : I am pasting my request string and the corresponding response..
Request:
http://my.mobfox.com/request.php?r_type=banner&rt=api&u=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%208_4%20like%20Mac%20OS%20X%29%20AppleWebKit%2F600.1.4%20%28KHTML%2C%20like%20Gecko%29%20Mobile%2F12H4125a&o_iosadvid=64E45D4E-B0FC-41FF-8A91-59D37BB27554&v=6.2.2&s=a7c07f113cc83e87e82f95f0ca8be1dc&iphone_osversion=8.4&r_random=21509&m=live&i=158.25.45.4&o_iosadvidlimit=0

Response:

<request type="textAd">
<htmlString>
<![CDATA[
<a href="http://my.mobfox.com/exchange.click.php?h=1b1125102425886d49fb0d2c50390007"><img src="http://cdn.manage.com/763/m_el_PHF_320x50_Sevens.gif" width="320" height="50"></a><img style="position:absolute; left: -10000px;" width="1" height="1" src="http://my.mobfox.com/exchange.pixel.php?h=1b1125102425886d49fb0d2c50390007"/>
]]>
</htmlString>
<clicktype>safari</clicktype>
<clickurl>
<![CDATA[
http://my.mobfox.com/exchange.click.php?h=1b1125102425886d49fb0d2c50390007
]]>
</clickurl>
<urltype>link</urltype>
<refresh>30</refresh>
<scale>no</scale>
<skippreflight>yes</skippreflight>
</request>

**Comment by nabriski** [comment]
This looks valid, do you have an example of an invalid response?

**Comment by harithahdasan** [comment]
@nabriski :Actually now I tested with my iOS device .For device ,click url is navigating to some pages.So I think I can avoid this issue na??

**Comment by nabriski** [comment]
Maybe there was a problem with a specific advertiser sending bum ads. If it happens again please send the markup.

**Comment by harithahdasan** [comment]
@nabriski :Ok thanks.
