### ISSUE TITLE
No code for finding the ip address of requesting device .

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#16]
Inside the mob fox iOS sdk there is no code for finding the ip address of the requesting device.I am setting the value for "i" as the default value that you mentioned in mob fox wiki.What should i do if I don't want the ip to be hard coded?

**Comment by nabriski** [comment]
you can use this: http://stackoverflow.com/questions/6807788/how-to-get-ip-address-of-iphone-programatically

We are working on adding this to the SDK in future versions.

**Comment by harithahdasan** [comment]
@nabriski :Ok fine ...But if I hard code my device's ip to the request I am getting noAd response(So getting ip address of phone programmatically won't solve the issue na?).But I am getting response when I set Mobfox default ip(178.190.64.146).Why mob fox not accepting my device's ip?

**Comment by nabriski** [comment]
on emulator you may be sending a local ip os similar.

**Comment by harithahdasan** [comment]
Yes. but now I am talking about device.When I put my device's ip in request string I m not getting BannerAd.But when I give ip =158.25.45.46(I don't remember from where I got this ip) right now I am getting BannerAd in my iphone4.And in some cases ip=178.190.64.146(default ip given in Mobfox wiki) I get Ad(Now not getting).Please give a solution for this..

**Comment by nabriski** [comment]
It depends on the demand in your Geo and the fill rate in general. You will not get a response for each request as the fill rate is still not 100%.

**Comment by harithahdasan** [comment]
I didn't ever get a response from mob fox when I set the ip to my device's ip.Not even once.So how can I avoid this issue?

**Comment by nabriski** [comment]
what is your ip?

**Comment by harithahdasan** [comment]
@nabriski :Hi ...192.168.0.144(my ip)

**Comment by nabriski** [comment]
This is a local (private) network ip that you probably got from your router, there is no way to geo target it so no ads are served.
https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces

**Comment by harithahdasan** [comment]
Ok ..I would like to know that is it necessary to consider the static ip address of the requesting device(because inside my iPhone no static ip is configured ,my phone is using the ip of the connected network )or can I proceed with the default ip provided by the mob fox.Will I able to display Ads on the iPhone in future(currently I am getting ads )

**Comment by nabriski** [comment]
We are working on making this ip parameter not necessary as we can read it from the request anyway.

**Comment by harithahdasan** [comment]
Ok..then I will continue with your default ip itself
