### ISSUE TITLE
How to access the  attribute value inside the tag "htmlstring"?

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#17]
Hi...From the below response I would like to get the value inside "a href" and "img src"  separately.Please tell what modification should be made on the code inside "SetUpAdFromXml "method

![screen shot 2015-07-27 at 12 49 17 pm](https://cloud.githubusercontent.com/assets/13059550/8900465/ed4f71b0-345d-11e5-9040-e57b0f03385c.png)

**Comment by harithahdasan** [comment]
Hi..Some one please give me a guidance...

**Comment by nabriski** [comment]
The ad returned is one HTML unit and the SDK does not cover getting the values separately as this is not needed to show the ad. If you need this granularity please use native ads.

**Comment by harithahdasan** [comment]
@nabriski :But inside the MFDTXMLElement.m there are functions to retrieve the attributes..And inside "setupAdfromXML" method there is a line of code which calls for attribute objectf or key "skipoverlaybutton".It always returns nil(0 key /Value pair).I just modified that line and replaced the "skipoverlaybutton"to "href".Why it still returns 0 key/value pairs.Below is the code portion that I am mentioning.....


![screen shot 2015-07-28 at 10 17 47 am](https://cloud.githubusercontent.com/assets/13059550/8923701/0617696e-3512-11e5-8873-b9f92da2ca1a.png)

**Comment by nabriski** [comment]
I think you are confusing attributes of the ```htmlstring``` xml element and the element's content:

```xml
<htmlstring skipoverlaybutton="true"> ... </htmlstring>
```
vs.
```xml
<htmlstring>
<![CDATA[
<a href="http://example.com">button</a>
]]>
 </htmlstring>
```
