### ISSUE TITLE
BannerAd not aligned properly in view

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#18]
Hi,The displayed banner Ad is not aligned properly inside the banner view.Please check the below screenshot..
![screen shot 2015-07-29 at 11 37 53 am](https://cloud.githubusercontent.com/assets/13059550/8951027/a59083c0-35e6-11e5-8466-97e5717b841c.png).
The yellow portion is the Webview.(I just replaced clear color to yellow)
How to make the banner Ad fit on the yellow portion.

**Comment by nabriski** [comment]
can you please post your integration code?

**Comment by harithahdasan** [comment]
integration code means?which portion of code?

**Comment by harithahdasan** [comment]
Is this the portion of code u asking?
[(UIWebView*)nextBannerView loadHTMLString:_htmlString baseURL:nil];
        
        if(![skipOverlay isEqualToString:@"1"]) { //create overlay only if necessary, to not interfere with custom events
            UIImage *grayingImage = [self darkeningImageOfSize:self.bannerView.frame.size];
        
            UIButton *button=[UIButton buttonWithType:UIButtonTypeCustom];
           
           [button setFrame:self.bannerView.bounds];
           
            
            [button addTarget:self action:@selector(tapThrough:) forControlEvents:UIControlEventTouchUpInside];
            
            [button setImage:grayingImage forState:UIControlStateHighlighted];
            button.alpha = 0.47;
        
            button.center = CGPointMake(roundf(self.bounds.size.width / 2.0), roundf(self.bounds.size.height / 2.0));
           button.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
        
            [self addSubview:button];

**Comment by nabriski** [comment]
Why is there a button sharing the same bounds as the banner?

**Comment by harithahdasan** [comment]
I don't know..Its mob fox code na..Is that causing the problem?

**Comment by nabriski** [comment]
no idea, but you can see in the wiki docs how to set up a banner where you want it.
https://github.com/mobfox/MobFox-iOS-SDK/wiki/Integrate-Banners-Version-7.x

**Comment by nabriski** [comment]
sorry didn't notice this was from our code base (:
I meant where is your code integrating the banner into your app?

**Comment by harithahdasan** [comment]
Hi..I am attaching the screenshot below..
![screen shot 2015-08-03 at 10 10 04 am](https://cloud.githubusercontent.com/assets/13059550/9030947/f73f7c96-39c7-11e5-9a04-3b544cbced24.png)

**Comment by nabriski** [comment]
Do set the banner x,y in the delegate as in the examples (don't see this part in the code sample)?

**Comment by harithahdasan** [comment]
Did you mean Appdelegate.m class?

**Comment by nabriski** [comment]
no, I mean MobFoxBannerViewDelegate

**Comment by harithahdasan** [comment]
Ok....
