### ISSUE TITLE
Why there have not MobFoxInterstitialViewController.m&MobFoxHTMLBannerView

### ISSUE THREAD

**Issue by zhengyi5134** [mobfox/MobFox-iOS-SDK#19]
![q1](https://cloud.githubusercontent.com/assets/10822616/8951400/ee83cb32-35ff-11e5-85ae-9fa4004c6a6d.jpg)

Can you tell me why ? Please~

**Comment by nabriski** [comment]
Hi,

How did you include the sdk?
Did you checkout our demo sdk? it has working examples for these classes.

**Comment by zhengyi5134** [comment]
The Demo is MobFox's official SDK

**Comment by nabriski** [comment]
I mean this: https://github.com/mobfox/MobFox-iOS-Demo
