### ISSUE TITLE
Creating MobFoxInterstitialAd crashes

### ISSUE THREAD

**Issue by dwxw** [mobfox/MobFox-iOS-SDK#2]
When attempting to create a MobFoxInterstitialAd, my application crashes with:

'NSInvalidArgumentException', reason: '**\* -[NSURL initFileURLWithPath:]: nil string parameter'

I'm creating the MobFoxInterstitialAd as

MobFoxInterstitialAd *interstitial = [[MobFoxInterstitialAd alloc] init:@"publisherId"];

I'm using the MobFoxSDKCore.embeddedframework directly in my project.  Could I be missing some dependencies?

Thanks.

**Comment by nabriski** [comment]
When you add the `MobFoxSDKCore.embeddedframework` it should also add the `MobFoxSDKCore.bundle` to your project, is that the case?

**Comment by dwxw** [comment]
Yep, that was it.  My project wasn't pointing at the bundle correctly.
