### ISSUE TITLE
Cant access the serverurl when setting it inside the source code itself...

### ISSUE THREAD

**Issue by harithahdasan** [mobfox/MobFox-iOS-SDK#21]
Hi..
I have modified the MobfoxBanner.m inside the source code . And set the server url in that class itself.But later when I run my demo project by using the framework build by using updated code .I am getting the message "Mobfox Banner: did fail to load ad: Error - no or invalid requestURL. Please set requestURL".How to solve this?

**Comment by nabriski** [comment]
I guess you should make sure the url you use is valid.

**Comment by harithahdasan** [comment]
ok
