### ISSUE TITLE
crash at - [WebViewJavascriptBridgeBase flushMessageQueue:] line 75

### ISSUE THREAD

**Issue by Fimius** [mobfox/MobFox-iOS-SDK#22]
We have a lot of crashes in Mobfox banner ads.
Crash log details:

Crashed Thread:  0
Application Specific Information: objc_msgSend() selector name: _log:json:

Thread 0 Crashed:
objc_msgSend + 28
-[WebViewJavascriptBridgeBase flushMessageQueue:](MFWebViewJavascriptBridgeBase.m:75)
-[MFWebViewJavascriptBridge webView:shouldStartLoadWithRequest:navigationType:](MFWebViewJavascriptBridge.m:162)
-[UIWebView webView:decidePolicyForNavigationAction:request:frame:decisionListener:] + 292

It is information from Hockeapp, but I can't reproduce it on my device yet.
Do you have any idea what could be the problem? We use Mopub integration.

**Comment by nabriski** [comment]
Thanks, will update.

**Comment by shimisheetrit** [comment]
Could you send me more information (sample code, or new project) to reproduce this crash?
Thanks

**Comment by Fimius** [comment]
As I said earlier I can't reproduce this crash. I can attach example of full crash log only. I have around 200K of the same logs for the last 5 days. It should be common issue. SDK version 2.2.7
[625fd5999f256b6916a6e56461f6fd4f.txt](https://github.com/mobfox/MobFox-iOS-SDK-Core-Lib/files/456566/625fd5999f256b6916a6e56461f6fd4f.txt)

**Comment by shimisheetrit** [comment]
I understand you cannot reproduce it. we did some changes that might resolve this crash, and only by running it with publisher project it can be sufficiently verified. but we want to examine it further and use implementation code. please try providing us MobFox integration code (from Hockeapp or any other tech side) it'll be helpful. let us know if it possible or what else can be done. thanks.

**Comment by nabriski** [comment]
Not using UIWebView in the banner anymore.
