### ISSUE TITLE
Interstitial Show Problem

### ISSUE THREAD

**Issue by kokteyldev** [mobfox/MobFox-iOS-SDK#23]
We implemented in a new project and getting this error when trying to show interstitial;
MobFox >> Interstitial >> cannot show as root uicontroller was not provided.

What is the reason for that? Thanks.

**Comment by shimisheetrit** [comment]
Did you declare MobFoxInterstitialAd with nil for rootViewController?
Make sure it's declared with self:
    self.mobfoxInterAd = [[MobFoxInterstitialAd alloc] init:MOBFOX_HASH_INTER withRootViewController:self];

**Comment by kokteyldev** [comment]
In our implementation <MobFoxInterstitialAdDelegate> and rootViewController are not the same objects. I am passing application's rootview controller as root view controller and self as delegate.
- (void)loadInterstitial {
  
  [MobFoxInterstitialAd locationServicesDisabled:YES];
  _interstitial = [[MobFoxInterstitialAd alloc] init:self.placement.adspaceId
                              withRootViewController:[UIApplication sharedApplication].keyWindow.rootViewController];
  _interstitial.delegate = self;
  [_interstitial loadAd];
  }

**Comment by shimisheetrit** [comment]
[UIApplication sharedApplication].keyWindow.rootViewController] returns nil, and this is the reason you are getting our warning in the console.
Try to use the code below for getting rootViewController:

```
MainViewController *rootController =(MainViewController*)[[(AppDelegate*)
                                                           [[UIApplication sharedApplication]delegate] window] rootViewController];

self.mobfoxInterAd = [[MobFoxInterstitialAd alloc] init:MOBFOX_HASH_INTER withRootViewController:rootController];
```

*\* MainViewController is your root view controller in view controller hierarchy. actually, it's the container view controller as: UINavigationController, UISplitViewController, and UIPageViewController.

**Comment by shimisheetrit** [comment]
MainViewController class name is just an example from Demo App.
