### ISSUE TITLE
MobFoxInlineVideoAd.h properties

### ISSUE THREAD

**Issue by condemned77** [mobfox/MobFox-iOS-SDK#23]
Hi there,

when I'm compiling my Xcode project with your SDK, Xcode warns me since there are a few properties with missing attributes.

   @property WebViewJavascriptBridge* bridge;
    @property NSString* longitude;
    @property NSString* latitude;
    @property NSString* demo_gender; //"m/f"
    @property NSString* demo_age;
    @property NSString* s_subid;
    @property NSString* sub_name;
    @property NSString* sub_domain;
    @property NSString* sub_storeurl;
    @property NSString* v_dur_min;
    @property NSString* v_dur_max;
    @property NSString* r_floor;
    @property BOOL autoplay;
    @property BOOL skip;

I'm not using ARC and the compiler tells that assign is assumed as attribute. However, for NSString it should be copy as far as I know (http://stackoverflow.com/questions/387959/nsstring-property-copy-or-retain).

I'm unsure about the WebViewJavaScriptBridge.

**Comment by nabriski** [comment]
Hi,

Can you please post the warnings you're getting? I'll happily fix it.

Thanks

**Comment by condemned77** [comment]
![screen shot 2015-08-17 at 15 08 15](https://cloud.githubusercontent.com/assets/2405937/9305463/dc482cc8-44f1-11e5-9c6c-1f795d61f859.png)

Is that sufficient?

**Comment by nabriski** [comment]
Yes, thanks. I'll try to upload a fix tomorrow.

**Comment by nabriski** [comment]
```WebViewJavascriptBridge* bridge``` made private as it should be. Fixed the others and pushed.
Should also appear in the MobFox control panel in about 30 minutes or so.
