### ISSUE TITLE
Integration of Mopub apart form MobFox SDK

### ISSUE THREAD

**Issue by condemned77** [mobfox/MobFox-iOS-SDK#24]
Hi there,

I've a request that is concerned with integrating the MobFox SDK next to the Mopub SDK.

When taking a look at the resource folder we can find the files MPCloseButtonX, etc. 
This file is included in both SDKs, the MobFox SDK and the Mopub SDK. 
![screen shot 2015-08-27 at 09 58 58](https://cloud.githubusercontent.com/assets/2405937/9515514/9f8ba338-4ca2-11e5-9736-a8d6b69704e5.png)

Thus, a build issue can occur if both SDKs are added to the Xcode project. You can find the issue described here:
http://stackoverflow.com/questions/13679710/not-a-png-filcommand-copypng-emitted-errors-but-did-not-return-a-nonzero-exit-co

Since you also resolved some naming conflicts with the Mopub SDK in a previous release, I'm wondering whether it would be possible to also rename this MPCloseButtonX... files?

Cheers
Michael

**Comment by nabriski** [comment]
better late then never. sorry, this one slipped by.
