### ISSUE TITLE
Admob adapter not work

### ISSUE THREAD

**Issue by MattiaConfalonieri** [mobfox/MobFox-iOS-SDK#25]
adMob adapter give error:

'GADMAdNetworkAdapterProtocol.h' file not found

**Comment by shimisheetrit** [comment]
'GADMAdNetworkAdapterProtocol.h' file is in Mediation Adapters directory which is distributed with the AdMob SDK. it's described in our docs, check out the link below. 

https://github.com/mobfox/MobFox-iOS-SDK/wiki/Adapters

**Comment by MattiaConfalonieri** [comment]
I have integrate last AdMob SDK via pods, but error persist

**Comment by MattiaConfalonieri** [comment]
AdMob SDK not longer seems contain Mediation Adapters, how can integrate the mediation? if i delete from GADMAdapterMobFox.h

#import "GADMAdNetworkAdapterProtocol.h"

it work ?

**Comment by shimisheetrit** [comment]
'Mediation Adapters' was added to the latest version v3.0.4. you can try to integrate it manually and check if the adapters works ( despite of using cocoa pods).

**Comment by MattiaConfalonieri** [comment]
v3.0.4??? i am using the v.7.15.0 for me this is the last and not contains 'Mediation Adapters'.

I don't understand what i do wrong...

**Comment by shimisheetrit** [comment]
I meant to MobFox SDK v3.0.4, just add 'Mediation Adapters' directory to your project and let me know if it works. I already sent mail to google support regarding to this issue, that it's missing in the SDK when integrating it manually and possibly using cocoa pods (as you claim).

**Comment by MattiaConfalonieri** [comment]
Thank you very much for your help, but unfortunately not work... if i integrate manually 'Mediation Adapters' i receive error of redefinition on GADMEnums.h and i can't remove it because error.

**Comment by MattiaConfalonieri** [comment]
Here my steps:

• Install manually MobFox SDK v3.0.4
• Add 'Mediation Adapters' directory 
• Go back with AdMob SDK until v7.13.1
• Inside GADMAdapterMobFox.h change "GoogleMobileAds/GADMAdNetworkAdapterProtocol.h" to #import "GADMAdNetworkAdapterProtocol.h"

Now everything seems work... let me now, please, if this is an acceptable solution?

**Comment by nabriski** [comment]
Hi,

We've contacted AdMob about this as our adapter is AdMob approved. I hope that this will be cleared in a few days as to how we are meant to interact with their latest lib.
In the mean time you can use the solution above.

Sorry for the trouble

**Comment by MattiaConfalonieri** [comment]
Ok let me know when is solved... and thank you very much for the help.

**Comment by shimisheetrit** [comment]
You can find 'Mediation' directory at the path GoogleMobileAdsSdkiOS-7.15.0/GoogleMobileAds.framework/Headers/Mediation.
As to implementing it with cocoa pods we are waiting for an answer from google.
I'll update you as soon as I get an unswer.

**Comment by delowarhym** [comment]
As a partner Github i like i want connect to https://github.com/mobfox/MobFox-iOS-SDK/issues/25.
