### ISSUE TITLE
Attempt to import "MobFoxAdLegacy.h" breaks build

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-iOS-SDK#27]
It seems that since version 3.0.7 of the iOS framework, `MobFoxInterstitialAd.h` attempts to import `MobFoxAdLegacy.h` on line 13. For me, this breaks the build, and I cannot find this file myself anywhere.

Has this file been accidentally omitted from the framework?

**Comment by nabriski** [comment]
Hi,



We will check, as we are about to release a small update today, we'll
include this fix as well.




On Mon, Dec 5, 2016, at 07:43 AM, rickydamelio wrote:

> It seems that since version 3.0.7 of the iOS framework,
> MobFoxInterstitialAd.h attempts to import MobFoxAdLegacy.h on line 13.
> For me, this breaks the build, and I cannot find this file myself
> anywhere.
> Has this file been accidentally omitted from the framework?



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/mobfox/MobFox-iOS-SDK/issues/27

**Comment by shimisheetrit** [comment]
Please try the new version v3.1.0  (just released today), that issue is resolved.

**Comment by ghost** [comment]
Yes, this has been fixed in v3.1.0. Thanks!
