### ISSUE TITLE
Module build warning

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-iOS-SDK#28]
It seems in the v3.1.0 release, Xcode generates warnings for building of the module.

<img width="400" alt="screen shot 2016-12-07 at 10 53 56 am" src="https://cloud.githubusercontent.com/assets/5070045/20949075/9f7418b4-bc6b-11e6-8831-10b18a04b967.png">

**Comment by shimisheetrit** [comment]
It's fixed in version v3.1.1 that we just released.
