### ISSUE TITLE
MobFoxInterstitialAdClosed not called when ad clicked

### ISSUE THREAD

**Issue by dwxw** [mobfox/MobFox-iOS-SDK#30]
If the ad is closed via the cross in the top right, the MobFoxInterstitialAdClosed callback fires as expected.  However if the ad is clicked, Safari is typically launched, quickly followed by the App Store.  The go back feature in the top left on iOS will only take you back to Safari.  If you then go back to your app the ad is gone, and so there is no means of closing it.  Closing the App Store and/or Safari doesn't trigger the MobFoxInterstitialAdClosed callback either.  I guess the ad should still be visible on the app so it can be closed.

**Comment by nabriski** [comment]
Hi,

Closing the ad is how it's meant to behave. But I agree the scenario you addressed is not handled very well by this behavior. We will discuss this and update this issue accordingly.

Thanks

**Comment by nabriski** [comment]
BTW, what do you "do" with the close event? I'm asking this as I want to take this into consideration when thinking about a solution.

**Comment by dwxw** [comment]
Thanks for the quick response.  I use the close event to tell my app that we're not showing an ad anymore.  Without it, it gets stuck thinking an ad is still on screen.  I figure I can workaround it by checking that if the app comes back from the background it was last active when an ad had been clicked.

**Comment by nabriski** [comment]
Fixed in 3.1.6
