### ISSUE TITLE
Add MobFoxSDK to Cocoapods Trunk

### ISSUE THREAD

**Issue by galip91** [mobfox/MobFox-iOS-SDK#31]
Hi,

I regularly update my pods and because MobFoxSDK isn't in the Cocoapod Trunk we have to manually point it to this github. But it takes a long time to download the source everytime i do 'pod update', even though I have fast internet. 
Isn't it possible to push your source to the Cocoapod Turnk (https://guides.cocoapods.org/making/getting-setup-with-trunk.html) so the 'pod update' instructions would speed up significantly?

**Comment by nabriski** [comment]
Yes, this is already on our TODO, should be done in the next few weeks. Nice to hear this feature is useful.

**Comment by nabriski** [comment]
I'll update this issue when we're done.

**Comment by galip91** [comment]
Any updates on this?

**Comment by nabriski** [comment]
Not yet, we are working on a major update but this didn't make it in.
I'll try to get someone to this "out of version"

**Comment by kokteyldev** [comment]
Nabriski its 5 minutes job for engineers like you; and will help us update our projects much faster.

Just create a pod with command 

pod lib create Mobfox

Then open podspec, paste following, edit values, and run pod lib lint, pod spec lint then push to trunk; pod trunk push.

viola

Pod::Spec.new do |s|
  s.name             = 'Mobfox'
  s.version          = '3.1.5'
  s.license          = { :type => 'Copyright', :text => <<-LICENSE
														Copyright 2016
														Mobfox. 
														LICENSE
														}
  s.homepage         = 'http://www.mobfox.com/'
  s.author           = { 'Mobfox Limited' => 'info@mobfox.com' }
  s.summary          = 'Mobfox SDK.'
  s.description      = 'Description.'

  s.source           = { :git => 'https://github.com/mobfox/MobFox-iOS-SDK/',
 								 :tag => s.version.to_s
 								}
  s.documentation_url = 'https://github.com/mobfox/MobFox-iOS-SDK/'
  s.platform 			= :ios
  s.ios.deployment_target = '7.0'
  s.vendored_frameworks = 'Libs/MobFoxSDKCore.framework'
  s.resource = 'Libs/MobFoxSDKCore.bundle'
  s.frameworks = 'AddressBook', 'AddressBookUI', 'AdSupport', 'AudioToolbox', 'AVFoundation', 'AVKit', 'CFNetwork', 'CoreGraphics', 'CoreLocation', 'CoreMedia', 'CoreMotion', 'CoreTelephony', 'EventKit', 'EventKitUI', 'Foundation', 'JavaScriptCore', 'MediaPlayer', 'QuartzCore', 'SafariServices', 'StoreKit', 'SystemConfiguration', 'Twitter', 'UIKit', 'WebKit'
  s.libraries = 'sqlite3', 'z'
  s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }
end

**Comment by nabriski** [comment]
Since you did 95% of the work for me, I'll just do it today. Thanks!

**Comment by kokteyldev** [comment]
I forgot to add headers :)

s.source_files = ''Libs/MobFoxSDKCore.framework/Headers/*.h'
s.public_header_files = ''Libs/MobFoxSDKCore.framework/Headers/*.h'

**Comment by nabriski** [comment]
thanks, I will check this anyway before pushing, of course

**Comment by nabriski** [comment]
Pushed to trunk.
```pod 'MobFoxSDK'``` is working.
