### ISSUE TITLE
MobFoxAd crashes on 10.3 betas

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-iOS-SDK#33]
It appears your framework is crashing repeatedly on all seeds of the iOS 10.3 beta. I have attached part of a crash report, but all reports suggest the same method is responsible.

> Date/Time:       2017-02-05T07:49:10Z
> Launch Time:     2017-02-05T07:49:07Z
> OS Version:      iPhone OS 10.3 (14E5230e)
> Report Version:  104
> 
> Exception Type:  SIGABRT
> Exception Codes: #0 at 0x18a19d014
> Crashed Thread:  0
> 
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[MFWKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'
> 
> Last Exception Backtrace:
> 0   CoreFoundation                       0x000000018b1a3fac 0x18b077000 + 1232812
> 1   libobjc.A.dylib                      0x0000000189c0853c 0x189c00000 + 34108
> 2   CoreFoundation                       0x000000018b1a3ef4 0x18b077000 + 1232628
> 3   WebKit                               0x0000000194bc43ec 0x194b97000 + 185324
> 4   WebKit                               0x0000000194c0310c 0x194b97000 + 442636
> 5   Silverlake-iPhone                    0x0000000100ba3390 -[MobFoxAd webView:decidePolicyForNavigationAction:decisionHandler:] (MobFoxAd.m:660)
> 6   Silverlake-iPhone                    0x0000000100bb4f60 -[MFWKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] (MFWKWebViewJavascriptBridge.m:138)
> 7   WebKit                               0x0000000194c00d2c 0x194b97000 + 433452
> 8   WebKit                               0x0000000194d42854 0x194b97000 + 1751124
> 9   WebKit                               0x0000000194d65c24 0x194b97000 + 1895460
> 10  WebKit                               0x0000000194d60a40 0x194b97000 + 1874496
> 11  WebKit                               0x0000000194bfe8c0 0x194b97000 + 424128
> 12  WebKit                               0x0000000194da6680 0x194b97000 + 2160256
> 13  WebKit                               0x0000000194bc6ed8 0x194b97000 + 196312
> 14  WebKit                               0x0000000194bc4900 0x194b97000 + 186624
> 15  WebKit                               0x0000000194bc7104 0x194b97000 + 196868
> 16  JavaScriptCore                       0x000000018fad4c24 0x18f12f000 + 10116132
> 17  JavaScriptCore                       0x000000018fad4efc 0x18f12f000 + 10116860
> 18  CoreFoundation                       0x000000018b1523c8 0x18b077000 + 897992
> 19  CoreFoundation                       0x000000018b151d38 0x18b077000 + 896312
> 20  CoreFoundation                       0x000000018b14f944 0x18b077000 + 887108
> 21  CoreFoundation                       0x000000018b07f9bc 0x18b077000 + 35260
> 22  GraphicsServices                     0x000000018caec074 0x18cae0000 + 49268
> 23  UIKit                                0x000000019142e984 0x1913ba000 + 477572
> 24  AFL iPhone                           0x00000001000f3ec8 main (main_iPhone.m:16)
> 25  ???                                  0x000000018a08d59c 0x0 + 0

**Comment by nabriski** [comment]
Hi,

Are you using the latest version of the SDK? I don't think we use this specific class anymore (```MFWKWebViewJavascriptBridge``` ).

**Comment by nabriski** [comment]
BTW, it appears to be in a lib we are using:
https://github.com/marcuswestin/WebViewJavascriptBridge/issues/267
But again, I don't think we are using this specific class.
