### ISSUE TITLE
Native ads not clickable

### ISSUE THREAD

**Issue by t3chno** [mobfox/MobFox-iOS-SDK#35]
Hi, I tried one year ago mobfox and I had this problem and now I'm trying again but still native ads are not clickable. I'm using Mopub as an upstreamer and with other networks I don't have this problem.

thanks

**Comment by nabriski** [comment]
Hi,

We'll take a look at this property in our adapter. Please follow this issue for updates.

**Comment by nabriski** [comment]
Hi, we decided to drop support for native through MoPub.
You can work with us directly for native where the ad is clickable.

Thanks
