### ISSUE TITLE
XCode 8.3.2 Compiler Issues

### ISSUE THREAD

**Issue by iWareDesigns** [mobfox/MobFox-iOS-SDK#36]
I am experiencing a number of problems with the iOS SDK when compiling under XCode 8.3.2

1.	In the “MobFox-iOS-SDK/MobFoxSDKCore.embeddedframework/MobFoxSDKCore.framework/Headers/MobFoxSDKCore.h” file at line 20 is “#import “MobFoxAdTest.h”.  I cannot find this include file anywhere, should that line be in the final MobFoxSDKCore.framework?

2.	In “MobFox-iOS-SDK/Adapters/AdMob/GADMAdapterMobFox.m” XCode 8 is warning me that the “dealloc” method at Line 263 might need a “[super dealloc];” call added.  Should this source file be compiled using ARC?  If I compile using ARC the warning disappears, or is the compiler warning correct?

3.	In “MobFox-iOS-SDK/MobFoxSDKCore.embeddedframework/MobFoxSDKCore.framework/Headers/MobFoxAd.h” XCode is warning me that the declaration at lines 50 and 51 are defaulting to “assign”.  Should the properties be “@property (nonatomic assign)”?

4.	And finally when linking the “MobFoxSDKCore.framework” to our Apps we get a number of warnings (Please see attached image “XCode 8 Linker Warnings.png”).  If I turn debug generation to DWARF only then the warning disappear, but I would prefer to keep the setting to DWARF and dSYM.
<img width="2219" alt="xcode 8 linker warnings" src="https://cloud.githubusercontent.com/assets/28161411/25544250/8f08f4b2-2c51-11e7-8bfe-070fd644964d.png">

**Comment by nabriski** [comment]
Hi,

We'll release a small update with a fix for these early next week. I will update this issue accordingly.

Thanks

**Comment by shimisheetrit** [comment]
Hi,

A new version 3.1.6e has been just released, all the issues you described are fixed besides the second issue of “[super dealloc];” and that is right arc should be in use in class declaration.
