### ISSUE TITLE
Disabling Location Services Query

### ISSUE THREAD

**Issue by iWareDesigns** [mobfox/MobFox-iOS-SDK#37]
Hi,

I just wanted to get clarification on the correct method of disabling location services.

I use AdMob Mediation and have implemented MobFox through AdMob's system.

The MobFox SDK and AdMob Adapter have been added to our projects okay.

When should the following lines of code be called?

        //  Disable mob fox location services
        [MobFoxAd locationServicesDisabled:YES];
        [MobFoxInterstitialAd locationServicesDisabled:YES];

At the moment I have placed the code in an initialisation function that is called once before any advertising views are created?  Is this correct?

Or should I add these to the GADMAdapterMobFox.m file after the banner or interstitial views are created?

Regards,

iWare Designs Ltd.

**Comment by nabriski** [comment]
Hi,

Yes, you only need to call it once for each type.
