### ISSUE TITLE
Update installation guide for Xcode 8

### ISSUE THREAD

**Issue by leolobato** [mobfox/MobFox-iOS-SDK#39]
The guide mentions:

>  Set `Embedded Content Contains Swift Code` to Yes.

That key (`EMBEDDED_CONTENT_CONTAINS_SWIFT`) has been deprecated on Xcode 8 and doesn't show on the default list of build settings. It has been replaced by `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES`.

According to someone mentioning [Xcode 8 beta 2 release notes](http://stackoverflow.com/a/39049584/67397):

> The new build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES replaces the use of EMBEDDED_CONTENT_CONTAINS_SWIFT. This setting indicates that Xcode should always embed Swift standard libraries in a target for which it has been set, whether or not the target contains Swift code. A typical scenario for using this setting is when a target directly uses or embeds another product which contains Swift code.

**Comment by shimisheetrit** [comment]
That's fine, we released the latest version with Xcode 8.3.1 so  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES defined in build settings. thanks for the update.
