### ISSUE TITLE
Can't not build with obj-c project with Xcode 8.3.2

### ISSUE THREAD

**Issue by billypchan** [mobfox/MobFox-iOS-SDK#40]
Hello all,

I got following error when I tried to build the project with iPhone SE. It can runs on simulator:

Showing Recent Messages
ld: 'Pods/MobFoxSDK/MobFoxSDKCore.embeddedframework/MobFoxSDKCore.framework/MobFoxSDKCore(MFDeviceExtention.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Thanks in advance!

**Comment by shimisheetrit** [comment]
For the static target MobFoxSDKCore bitcode isn't enabled, you should disable it. go to Build Settings and set Enable Bitcode to No.

**Comment by billypchan** [comment]
Hi shimisheetrit,
What should I do if I want to install with cocoapods?

**Comment by shimisheetrit** [comment]
The same when using cocoapods. disable Bitcode in Build Settings.
