### ISSUE TITLE
GADMAdapterMobFox duplicated files

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [mobfox/MobFox-iOS-SDK#41]
Hi,

I'm trying to integrate MobFox Admob adapter but inside the project the files GADMAdapterMobFox.h/.m are duplicated inside the Adapters folder and also inside the Samples/AdMobAdapterSample/AdMobAdapterSample.

Since they are different which version is the correct one ?

BR,

**Comment by nabriski** [comment]
Hi,

Please use this folder: https://github.com/mobfox/MobFox-iOS-SDK/tree/master/Adapters/AdMob
We will fix this duplication soon.

**Comment by vitorhugomagalhaes** [comment]
Hi,

Thanks. 

Another error I'm getting when using the pod version is that MFEventsHandler.h is not exposed in the public headers.

Is the pod deprecated ? 

BR,

**Comment by vitorhugomagalhaes** [comment]
As a side note, I decided to use the latest release from this repo.

The module could not be compiled becaused MobFoxAdTest.h is not added to MobFoxCore.h

I've added the missing import and it works. 

Still, I'm not sure if the MobFoxAdTest.h is supposed to be there.

Could you please check this ?

Thanks,

**Comment by shimisheetrit** [comment]
Hi,

Have you integrated the SDK manually or using cocoa pods?

**Comment by vitorhugomagalhaes** [comment]
Hi,

I've tried using cocoapods but got the MFEventsHandler error.

Now I'm trying it manually but got the missing MobFoxAdTest import error.

Just trying to make this work :)

**Comment by nabriski** [comment]
ok, we're trying to reproduce and fix this. Will update this issue.

**Comment by nabriski** [comment]
Uploaded a fix and also updated cocoapods. Sorry, this is what we get for rushing things this week.
