### ISSUE TITLE
armv7s arch - iPhone 5, iPhone 5c, iPad(4G) is not supported

### ISSUE THREAD

**Issue by igavrysh** [mobfox/MobFox-iOS-SDK#46]
when running the following query against both, MobFoxSDKCore and MobFoxSDKCoreDynamic:
`lipo -info MobFoxSDKCoreDynamic`
I receive the following output:
`Architectures in the fat file: MobFoxSDKCore are: i386 armv7 x86_64 arm64 `
`Architectures in the fat file: MobFoxSDKCoreDynamic are: x86_64 i386 armv7 arm64`
It means that armv7s is not supported(iPhone 5, iPhone 5c, iPad(4G))
Can you elaborate on this? why these arch was dropped out from Release build?

**Comment by nabriski** [comment]
Hi,

I think it's due to XCode changes in the default archs. We'll issue an update with a fix soon.

Itamar

**Comment by nabriski** [comment]
Hi, please try the build below and tell me if it works for you.

```Architectures in the fat file: MobFoxSDKCore.embeddedframework/MobFoxSDKCore.framework/MobFoxSDKCore are: i386 armv7 armv7s x86_64 arm64```

[armv7s.zip](https://github.com/mobfox/MobFox-iOS-SDK/files/1298281/armv7s.zip)

**Comment by igavrysh** [comment]
Yep, it seems that armv7s is no longer in the list of $(ARCHS_STANDARD) variables. Now, using the file you attached, armv7s arch is included into the build.

**Comment by nabriski** [comment]
ok, we'll include this in our next bug fix release and then I'll close this issue.

**Comment by igavrysh** [comment]
Thanks

**Comment by nabriski** [comment]
added in 3.1.8c
