### ISSUE TITLE
Module Debugging Enabled in Release Build of framework

### ISSUE THREAD

**Issue by iWareDesigns** [mobfox/MobFox-iOS-SDK#56]
Hi,

I am currently updating our advertising SDK's to the latest versions and have a number of warnings being generated with with the latest 3.1.9c framework at link time.

I have attached a screen grad of the warning, it would seem that the redistributable version of the framework has been built with "Module Debugging Enabled".

<img width="1235" alt="screen shot 2017-11-25 at 12 15 11" src="https://user-images.githubusercontent.com/28161411/33230418-e87ecace-d1da-11e7-8acd-59896a142d73.png">

Regards,

Gavin
iWare Designs Ltd.

**Comment by nabriski** [comment]
Hi,
Sorry about that, will push a correction tomorrow.

**Comment by shimisheetrit** [comment]
Hi,
Please try the attached SDK core and let us know if the warnings disappeared (CLANG_ENABLE_MODULE_DEBUGGING set to 'No' is one of the changes that has been made).
[MobFox-iOS-SDK-3.1.9c-binaries.zip](https://github.com/mobfox/MobFox-iOS-SDK/files/1503837/MobFox-iOS-SDK-3.1.9c-binaries.zip)

Regards,
Shimi

**Comment by iWareDesigns** [comment]
Hi,

All of the warnings have disappeared.  Thank you.

Regards,

Gavin
iWare Designs Ltd.

**Comment by shimisheetrit** [comment]
Fixed in 3.2.0
