### ISSUE TITLE
missing architecture x86_64

### ISSUE THREAD

**Issue by sphilipakis** [mobfox/MobFox-iOS-SDK#57]
running `lipo -info ./MobFoxSDKCoreDynamic.framework/MobFoxSDKCoreDynamic`
on the v3.1.9c release returns
`Architectures in the fat file: ./MobFoxSDKCoreDynamic.framework/MobFoxSDKCoreDynamic are: armv7 arm64`
Which prevents linking for simulator.

**Comment by nabriski** [comment]
Hi,
We're intending to release an update this week. I'll try to include this fix as well.

**Comment by sphilipakis** [comment]
Great! You may also want to make sure that #55 will be solved with this release, right now it's not allowing archiving when you use 3.1.9c via cocoapods.

**Comment by nabriski** [comment]
Fixed in ```3.2.0```
