### ISSUE TITLE
crashing while presenting modal view controller on any view controller

### ISSUE THREAD

**Issue by shatru-git** [mobfox/MobFox-iOS-SDK#58]
getting crash on MobFoxTagInterstitialAd.m line 78
Fatal Exception: NSInvalidArgumentException
Application tried to present modally an active controller <ViewController: 0x101980e00>.

I m using pod 'MobFoxSDK','~> 3.1.9'

**Comment by nabriski** [comment]
Hi,

Did you try: ```pod 'MobFoxSDK','3.1.9c'```?
I think that our versioning system does not always agree with Cocoapods (we'll fix this) so you may not be getting the latest.

**Comment by shatru-git** [comment]
Will it properly work if I integrate sdk manually ?

**Comment by nabriski** [comment]
I believe so.

**Comment by nabriski** [comment]
You an bump to it to 3.2.0 with the former setting ``` 'MobFoxSDK','~> 3.2.0'```. We'll adhere to the cocoapod rules from now on.
