### ISSUE TITLE
Moat framework not included in release binaries

### ISSUE THREAD

**Issue by andre-arsenault** [mobfox/MobFox-iOS-SDK#61]
In subsequent releases, please include `MATMoatMobileAppKit.framework` in the release binary zip file so that users don't need to clone/download the file manually. The release binary zip should be self-contained imho.

**Comment by shimisheetrit** [comment]
Hi,
MATMoatMobileAppKit.framework added, and now binaries zip file contains it.

Regards,
Shimi

**Comment by andre-arsenault** [comment]
Great, thanks.
