### ISSUE TITLE
Location Services

### ISSUE THREAD

**Issue by dwxw** [mobfox/MobFox-iOS-SDK#66]
We don't wish to use location services, so have added `[[MFLocationServicesManager sharedInstance] stopFindingLocation];` before requesting an ad.  However if you have location services disabled in the global settings (Settings/Privacy), the first call to the SDK launches the system popup requesting location services to be enabled.  I'm assuming if I'm asking the SDK not to use location, then it shouldn't need to have location services enabled.

**Comment by nabriski** [comment]
The fix for this will be included in our next release, currently scheduled for early next week.
