### ISSUE TITLE
CocoaPods has only 3.2.0 version of SDK

### ISSUE THREAD

**Issue by ivanov84** [mobfox/MobFox-iOS-SDK#69]
Could you fix latest version of mobfox in CocoaPods repository?

**Comment by nabriski** [comment]
Hi,

The latest version I pushed to Cocoapods is the latest - 3.4.4. Just verified it by trying to push again:
```shell
Validating podspec
 -> MobFoxSDK (3.4.4)

[!] Unable to accept duplicate entry for: MobFoxSDK (3.4.4)
```
On our Cocoapods [page](https://cocoapods.org/pods/MobFoxSDK) the latest is 3.4.3 but I guess this page is not up to date.

Where did you see 3.2.0 is the latest? did you try to install 3.4.4?

Thanks

**Comment by ivanov84** [comment]
@nabriski When I enter `pod 'MobFoxSDK','3.4.4'` or pod `'MobFoxSDK','3.4.3'` and run command `pod install` I see error: [screenshot](https://ibb.co/cVGOuS)

**Comment by nabriski** [comment]
Strange, just run it on a demo project and it succeeded:
```shell
pod install
Analyzing dependencies
Downloading dependencies
Installing MobFoxSDK 3.4.4 (was 3.3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Automatically assigning platform `ios` with version `10.2` on target `TestCoco` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Did you try the ```pod repo update``` it recommends in your installation ?

**Comment by ivanov84** [comment]
@nabriski after new cocoapods 1.5.2 - all crashed......... I'm trying to fix.

**Comment by ivanov84** [comment]
@nabriski after hours of solving problem I managed to solve it. And installed 3.4.4 version. Please delete this ticket. Thanks.

**Comment by nabriski** [comment]
sorry to hear it was such a drag. closing ticket
