### ISSUE TITLE
Missing MobFoxSDKCore.framework 	

### ISSUE THREAD

**Issue by dwxw** [mobfox/MobFox-iOS-SDK#70]
Hello,

Building with CocoaPods is currently broken for me.  The MobFoxSDKCore.framework is missing in Github.  The file is there in master, but the tags (3.4.4) don't have this file so #import <MobFoxSDKCore/MobFoxSDKCore.h> fails.

Thanks,
David.

**Comment by nabriski** [comment]
ok, bumped the tag, please try:
```
pod 'MobFoxSDK','3.4.4-b'
```

**Comment by dwxw** [comment]
Okay thanks, I'm now getting MobFoxSDKCore.embeddedframework.  Maybe it's unrelated but my app now crashes shortly after loading an interstitial ad:
MobFox wf request >> dealloc
-[__NSArrayM objectForKeyedSubscript:]: unrecognized selector sent to instance 0x60c00005b3f0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM objectForKeyedSubscript:]: unrecognized selector sent to instance 0x60c00005b3f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105cf21e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000104f40031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105d73784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000105c74898 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000105c74278 _CF_forwarding_prep_0 + 120
	5   ObjC SmartAds Example               0x000000010449e0f3 __30-[MobFoxInterstitialAd loadAd]_block_invoke_2 + 288
	6   libdispatch.dylib                   0x000000010ac43807 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010ac44848 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010ac4f92b _dispatch_main_queue_callback_4CF + 628
	9   CoreFoundation                      0x0000000105cb4c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x0000000105c78ea6 __CFRunLoopRun + 2342
	11  CoreFoundation                      0x0000000105c7830b CFRunLoopRunSpecific + 635
	12  GraphicsServices                    0x000000010b72ea73 GSEventRunModal + 62
	13  UIKit                               0x00000001080630b7 UIApplicationMain + 159
	14  ObjC SmartAds Example               0x00000001044349b1 main + 145
	15  libdyld.dylib                       0x000000010acc1955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any idea?

**Comment by MosheNe** [comment]
Hi David,
We tried to produce unfortunately without success
1. are you using special configuration ?
2. are you using special adapters ?
3. step for us to reproduce ?

**Comment by dwxw** [comment]
I've found I can do it using your DemoApp, starting it and selecting Video(Int) causes the crash.  Using Xcode 9.3.1.

**Comment by MosheNe** [comment]
Should be fixed now.
Can you please retry the test (might need to delete and re-install app to clear cache),  and confirm it's ok.
Thanks!

**Comment by dwxw** [comment]
Yes, that's working now, thank you.

**Comment by MosheNe** [comment]
Thanks
