### ISSUE TITLE
Adapter files are not linked - error in logs

### ISSUE THREAD

**Issue by ivanov84** [mobfox/MobFox-iOS-SDK#71]
Logs:
`<Notice>: <Google> Cannot find an ad network adapter with the name(s): GADMAdapterMobFox. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.`

Could you help me how to add files:

**GADMAdapterMobFox.h
GADMAdapterMobFox.m
RewardedAdmobAdapter.h
RewardedAdmobAdapter.m**

I dragged them to the Pod directory. But it does not work.

My Xcode screenshots:
[pod](https://ibb.co/kYK9RJ)
[main project](https://ibb.co/ggtsfd)

I develop app with cordova so I don't quite well understand Xcode programming....

To add mediation plugins I use cocoapods

for example:
```
	pod 'GoogleMobileAdsMediationInMobi'
	pod 'GoogleMobileAdsMediationUnity'
	pod 'GoogleMobileAdsMediationMyTarget'
	pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
	pod 'Flurry-iOS-SDK/FlurryAds' #Analytising Pod
	pod 'AdMobMediationAdapterFlurry','~>8'
	pod 'MobFoxSDK','3.4.4-b'
```

All mediation adapters work except for MobFox

**Comment by nabriski** [comment]
Hi,
Our tech support will help you later today.
Did you try this guide: https://github.com/mobfox/MobFox-iOS-SDK/wiki/Adapters#admob ?

**Comment by shahafss** [comment]
Hi Ivanov,
I've made you a short video showing how to add the adapter files to an iOS project.
https://youtu.be/ob1xXDIrfsY

LMK if you're having any more difficulties.

-Shahaf

**Comment by ivanov84** [comment]
@shahafss Thank you so much! You are the fastest man in the world!!! 😄😄😄
