### ISSUE TITLE
Add Native Ad type support to adapters

### ISSUE THREAD

**Issue by ogres** [mobfox/MobFox-iOS-SDK#72]
Currently none of the adapters support native ad type ( https://github.com/mobfox/MobFox-iOS-SDK/wiki/Adapters ).

It would be very helpful to have native ad support as well.

**Comment by nabriski** [comment]
Hi,

We cannot support AdMob native as it has to be an official native adapter and the business terms are not set for that. 
If you are using MoPub, it may be possible. If so, please provide us with your native MoPub integration code and we'll try to weigh the amount of effort needed to support this.

Thanks,
Itamar

**Comment by ogres** [comment]
Unfortunately I do not have any integration between MoPub - MobFox for now. I am using other network adapters via Mopub and wanted to add Mobfox as well ...

**Comment by nabriski** [comment]
Hi,

Sorry, I meant your MoPub code - the way you create and use the native ad in MoPub. We need to know what to build to accommodate this on the adapter side.

Thanks

**Comment by ogres** [comment]
My bad, I misunderstood.

Client code is very simple, you just provide list of supported mediation events.
Mediated networks are defined as "Custom Events".

Here is a guide how to create a new one:
https://developers.mopub.com/docs/ios/custom-events/

Here is a working Custom Event from 3rd party ad provider:
https://github.com/myTargetSDK/mytarget-ios/tree/master/mediation/mopub/native

**Comment by nabriski** [comment]
Hi,

Yes, of course, we already have custom events for MoPub in banner and interstitial. For native it's a bit more complicated (https://developers.mopub.com/docs/ios/custom-events/#quick-start-for-native-ads) so I wanted to see an example of how you use native ads in MoPub (disregarding mediation). Just the code you use to init, call and use the MoPub native ad.
If it's something that the reference implementation you've sent us covers then it won't be a problem.

Thanks

**Comment by ogres** [comment]
Here is a small example:

    let settings = MPStaticNativeAdRendererSettings()
    settings.renderingViewClass = SomeAdView.self // here goes the type of the UIView subclass that will render the ad.

    let staticRenderer = MPStaticNativeAdRenderer.rendererConfiguration(with: settings)
    staticRenderer.supportedCustomEvents = ["MPMoPubNativeCustomEvent", "FacebookNativeCustomEvent", "MTRGMopubNativeCustomEvent"] // Here we provide the list of Custom Events for mediations, usually a class name.
    
    let adRequest = MPNativeAdRequest(adUnitIdentifier: unit_ID, rendererConfigurations: [staticRenderer])
    adRequest?.start(completionHandler: { (_, ad, error) in
        // Handle response for ad request
    })

It is also possible to have a custom renderer for specific mediation, for examle Google's AdMob does have one.
To use it, we create a renderer with `MPGoogleAdMobNativeRenderer.rendererConfiguration(with: settings)` method and just add to `rendererConfigurations` parameter for `MPNativeAdRequest`

**Comment by nabriski** [comment]
Thanks, I'm adding this to our back log and will update this issue with our progress.

**Comment by ogres** [comment]
Thank you!

**Comment by OfirKa** [comment]
Hello @ogres,
Native ad adapter for MoPub are now available.
Please refer to our documents for installing instructions - 

https://mobfox.atlassian.net/wiki/spaces/PUMD/pages/512819289/MoPub-iOS
