### ISSUE TITLE
Getting Error: "Could not connect to the server."

### ISSUE THREAD

**Issue by wajahatiqbal** [mobfox/MobFox-iOS-SDK#74]
All the AdMob Ads are working fine with the demo application but whenever I click the MobFox ads (Banner, Interstitial, Video) with inventory hashes for the test ads, I get this:

`MobFoxAdDidFailToReceiveAdWithError: Error Domain=MobFoxJSContext Code=1 "Could not connect to the server." UserInfo={NSLocalizedRecoverySuggestion=Could not connect to the server., NSLocalizedDescription=Could not connect to the server., NSLocalizedFailureReason=Could not connect to the server.}
`

**Comment by nabriski** [comment]
Hi,

Could you please send us a network log such as from the "Charles Proxy" app?

Thanks

**Comment by wajahatiqbal** [comment]
<img width="1137" alt="screen shot 2018-08-27 at 5 35 13 pm" src="https://user-images.githubusercontent.com/19972722/44660054-cfb12000-aa1f-11e8-9d9c-fe3b13b05cf9.png">
<img width="1140" alt="screen shot 2018-08-27 at 5 35 32 pm" src="https://user-images.githubusercontent.com/19972722/44660060-d2137a00-aa1f-11e8-9a6f-ad0756f4078a.png">

I am not much familiar with Charles Proxy but this is the response being given on clicking the banner and interstitial ads. Are these enough or should I send something else?

**Comment by nabriski** [comment]
Which country are you making the request from? 
can you try with a VPN to change to another country?

**Comment by wajahatiqbal** [comment]
I was making requests from Pakistan.
Changed the country and it worked.
Thanks a lot.

**Comment by nabriski** [comment]
Great, I will forward this to our server team to give a proper message that is country based in the future.
