### ISSUE TITLE
Admob adapter doesn't work with latest Google-Mobile-Ads-SDK

### ISSUE THREAD

**Issue by OngoGablo** [mobfox/MobFox-iOS-SDK#76]
When using pod 'MobFoxSDK_AdMobAdapter' with pod 'Google-Mobile-Ads-SDK', my build fails with the following error.

> ld: warning: directory not found for option '-FMobFoxSDK'
> Undefined symbols for architecture arm64:
>   "_GADCustomEventParametersServer", referenced from:
>       -[RewardedAdmobAdapter requestRewardBasedVideoAd] in MobFoxSDK_AdMobAdapter(RewardedAdmobAdapter.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I need to downgrade the Google-Mobile-Ads-SDK from version 7.36.0 to version 7.32.0 to get rid of this error.

**Comment by OfirKa** [comment]
Hello @OngoGablo ,
Thank you for reporting this issue. 
It was forwarded to AdMob and we will let you know as soon as we have a solution.

**Comment by Khronoss** [comment]
@OfirKa 
Hi, is there any update on this issue ? I'm having the same, but using another adapter

**Comment by OfirKa** [comment]
@Khronoss 
Unfortunately we are still trying to figure it out with AdMob.

What kind of adapter you are using while getting the same behavior?

**Comment by Khronoss** [comment]
Hi ! Thank you for your quick answer :)

The error appeared on the VidCoin's adapter which can be found [here on github](https://github.com/VidCoin/Vidcoin-AdMob-Adapter) (unfortunately it's the framework itself, the sources are private)

**Comment by OfirKa** [comment]
Hello @OngoGablo @Khronoss,
According to AdMob this issue is fixed and should be released on their next version.
Have a great week,
Ofir

**Comment by Khronoss** [comment]
Nice to read that ! :) Thank you a lot for your support @OfirKa

**Comment by OngoGablo** [comment]
Thanks for contacting Admob. Their new SDK (version 7.38.0) was released yesterday but it still gives this issue, so hopefully the fix is included in the next version.

**Comment by OfirKa** [comment]
I saw the release this morning, figured out it still has the same issue and already contact them regarding it.

**Comment by OfirKa** [comment]
@OngoGablo,
AdMob confirmed that this issue should be solved in the next version, that should be released next week.

**Comment by OfirKa** [comment]
Hello @OngoGablo and @Khronoss,
I am very glad to inform you that AdMob have fixed the issue. AdMob's version 7.39 is working with MobFox adapters without causing linker errors. 
At the moment, you can install it manually but we will add AdMob's version to our next release which means you will then be able to install it via cocoapods

Thank you,
Ofir

**Comment by OngoGablo** [comment]
Thanks, I tried it and it works!

**Comment by OfirKa** [comment]
Great!
