### ISSUE TITLE
Pod conflicting names: mobfoxsdkcore.framework and matmoatmobileappkit.framework

### ISSUE THREAD

**Issue by jonameson** [mobfox/MobFox-iOS-SDK#77]
We are trying to include the SDK and admob adapter but we are getting the following errors. Any ideas why? Not even sure if this would be the place to post this.

----
_**Using following pods:**_

>  pod 'MobFoxSDK','3.6.0'
>  pod 'MobFoxSDK_AdMobAdapter','3.5.1'

----
**_Error log:_**
> [!] The 'Pods-AppName' target has frameworks with conflicting names: mobfoxsdkcore.framework and matmoatmobileappkit.framework.

**Comment by nabriski** [comment]
Hi,
Our iOS dev will try and reproduce this and update this issue. 

In the mean time, not sure if this will help, but I'd try to match the sdk and adapter versions:
pod 'MobFoxSDK','3.6.0'
pod 'MobFoxSDK_AdMobAdapter','3.6.0'

**Comment by jonameson** [comment]
Ah ok I'll check. 

Side questions... Is the following admob adapter here the latest?
https://github.com/mobfox/MobFox-iOS-SDK/tree/master/Adapters/AdMob

**Comment by nabriski** [comment]
For a definitive answer I would wait for our iOS dev, but from what I see, this is the version that was used in adapter's 3.6.0 podspec. It's most probably the latest.

**Comment by OfirKa** [comment]
Hey @jonameson,
pod 'MobFoxSDK','3.6.0' is already included in the pod 'MobFoxSDK_AdMobAdapter','3.5.1'.
There is no need to declare them both.

Please you pod 'MobFoxSDK_AdMobAdapter','3.5.1' alone.
Ofir

**Comment by jonameson** [comment]
@OfirKa I had a feeling that was happening. Thanks for clearing it up! Consider this ticket resolved.

**Comment by OfirKa** [comment]
Sure!
